### ISSUE TITLE
setup issues

### ISSUE THREAD

**Issue by roccojonack** [Minres/SystemC-Quickstart#1]
I always wanted to do this:-)

2 quick comments about things that I noticed:

- for me the conan default profile pointed to the 4.8 compiler and the default on the Ubuntu VM is 6.3. It took me a while before realizing where to change this (~/.conan/profiles/default). Probably good to mention.
- the README is missing one make step before running the executable. Maybe adding reference output or "you should see blabla at the end" could be useful

**Comment by eyck** [comment]
Hmm, `cmake --build .` should build the example. Could you check that?

**Comment by roccojonack** [comment]
Yes, you are right. I had done cmake without the build option. I guess going back and forth between README and shell I missed the additional option --build.
