### ISSUE TITLE
systemcverification/2.0.1: Not found

### ISSUE THREAD

**Issue by amal-khailtash** [Minres/SystemC-Quickstart#2]
After JFron bintray changes, build processes is broken.  I changed the requirements to:

```
[requires]
systemc/2.3.3
systemcverification/2.0.1
```

But Seems like systemcverification is not released.  This is related to the recipes I think: https://github.com/Minres/conan-recipes

**Comment by eyck** [comment]
I fixed the CMakeLists.txt to either use conan (via the https://raw.githubusercontent.com/conan-io/cmake-conan/v0.16.1/conan.cmake file) or using SYSTEMC_HOME.
Moreover the conan remote setting has been added to point to the right repository

**Comment by amal-khailtash** [comment]
This is working great.  Thank you.
