### ISSUE TITLE
Minres Conan Remote Seems Down

### ISSUE THREAD

**Issue by tianrui-wei** [Minres/SystemC-Quickstart#3]
Hi,

Thanks for having this awesome project open sourced! I was trying it out when I encountered the following issue

```
[shell]$ cmake .. -DCMAKE_BUILD_TYPE=Release
-- Conan: checking conan executable
-- Conan: Found program /home/.local/bin/conan
-- Conan: Version found Conan version 1.53.0

-- Conan: Adding minres remote repository (https://artifactory.minres.com/artifactory/api/conan/oss) verify ssl (True)
-- Conan: checking conan executable
-- Conan: Found program /home/.local/bin/conan
-- Conan: Version found Conan version 1.53.0

-- Conan executing: /home/.local/bin/conan install . --build missing --settings build_type=Release --settings compiler=gcc --settings compiler.version=9 --settings compiler.libcxx=libstdc++11 --settings compiler.cppstd=14
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

systemc-scv/2.0.1: Not found in local cache, looking in remotes...
systemc-scv/2.0.1: Trying with 'conancenter'...
systemc-scv/2.0.1: Trying with 'minres'...
ERROR: Unable to find 'systemc-scv/2.0.1' in remotes
CMake Error at build/conan.cmake:631 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  CMakeLists.txt:34 (conan_cmake_install)
```

It seems the minres url in the cmakelist is down. Do you have any tip?

**Comment by eyck** [comment]
Indeed the artifactory was hanging. It only hosts 2 packages anymore as we moved most of our C++ packages to [Conan Center](https://conan.io/center). So we will update this project soon.
Artifactory should work again.

**Comment by tianrui-wei** [comment]
~~Hi Eyck,~~

~~Thank you for your prompt response. Can we leave this issue open in the meantime until the packages are pushed onto Conan upstream?~~

~~Thanks~~

edit: nvm, thanks for updating the readme. It's working atm. Thanks for the timely help again!

**Comment by eyck** [comment]
Please note: the conan repo has been moved to https://git.minres.com/api/packages/Tooling/conan. This is already reflected at https://github.com/Minres/SystemC-Quickstart/blob/master/CMakeLists.txt#L25. So please keep this in mind.

**Comment by tianrui-wei** [comment]
Thanks @eyck, appreciate the timely fix
